"""renaming birthday column in student model

Revision ID: 5c748e524133
Revises: 01835012ba9b
Create Date: 2023-12-05 20:53:01.191939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c748e524133'
down_revision = '01835012ba9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholars', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.drop_index('ix_students_name', table_name='scholars')
    op.create_index(op.f('ix_scholars_name'), 'scholars', ['name'], unique=False)
    op.drop_column('scholars', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholars', sa.Column('birthday', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_scholars_name'), table_name='scholars')
    op.create_index('ix_students_name', 'scholars', ['name'], unique=False)
    op.drop_column('scholars', 'birth_date')
    # ### end Alembic commands ###
